config/routes.rb
Myneighborhoodis::Application.routes.draw do
  resources :neighborhoods do 
    resources :submissions
  end
  root to:"neighborhoods#index"
end

app/models/descriptor.rb
class Descriptor < ActiveRecord::Base
  belongs_to :submission
end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  has_many :submissions
  accepts_nested_attributes_for :submissions
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :neighborhood
  has_many :descriptors
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  
  # GET /neighborhoods
  # GET /neighborhoods.json
  def index
    @neighborhoods = Neighborhood.all
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController


  # GET /submissions/new
  def new
    @neighborhood = Neighborhood.find(params[:neighborhood_id])
    @submission = @neighborhood.submissions.build
  end


  # POST /neighborhoods
  # POST /neighborhoods.json
  def create
    @neighborhood = Neighborhood.find(params[:neighborhood_id])
    @submission = @neighborhood.submissions.build(submission_params)

    respond_to do |format|
      if @submission.save
        format.html { redirect_to @neighborhood, notice: 'Submission was successfully created.' }
        format.json { render action: 'show', status: :created, location: @submission }
      else
        format.html { render action: 'new' }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def submission_params
    params.require(:submission).permit(:submitter_name, :descriptor_attributes=>[:adjective])
  end

end  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myneighborhoodis</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/neighborhoods/_form.html.erb
<%= form_for(@neighborhood) do |f| %>
  <% if @neighborhood.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@neighborhood.errors.count, "error") %> prohibited this neighborhood from being saved:</h2>

      <ul>
      <% @neighborhood.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
		
  <div class="actions">
	  <%= f.submit %>
  </div>
	
	
<% end %>

app/views/neighborhoods/edit.html.erb
<h1>Editing neighborhood</h1>

<%= render 'form' %>

<%= link_to 'Show', @neighborhood %> |
<%= link_to 'Back', neighborhoods_path %>

app/views/neighborhoods/index.html.erb
<h1>All the Hoods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @neighborhoods.each do |neighborhood| %>
      <tr>
        <td><%= neighborhood.name %></td>
        <td><%= link_to 'Show', neighborhood %></td>
        <td><%= link_to 'Edit', edit_neighborhood_path(neighborhood) %></td>
        <td><%= link_to 'Delete', neighborhood, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<td><%= link_to 'Add Description', new_neighborhood_submission_path(neighborhood) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Neighborhood', new_neighborhood_path %>

app/views/neighborhoods/new.html.erb
<h1>New neighborhood</h1>

<%= render 'form' %>

<%= link_to 'Back', neighborhoods_path %>

app/views/neighborhoods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @neighborhood.name %>
</p>

<%= link_to 'Edit', edit_neighborhood_path(@neighborhood) %> |
<%= link_to 'Back', neighborhoods_path %>
<%= link_to 'Add Description', new_neighborhood_submission_path(@neighborhood) %>

app/views/submissions/_form.html.erb
<%= form_for([@neighborhood, @submission]) do |f| %>
  <% if @submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% @submission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
		<%= f.label :submitter_name %><br>
 		<%= f.text_field :submitter_name %>
	</div>

	<%= f.fields_for :descriptors, @submission.descriptors.build do |descriptor_fields| %>
  	Adjective: <%= descriptor_fields.text_field :adjective %>
  <% end %>
	
  <div class="actions">
	  <%= f.submit %>
  </div>
	
<% end %>

app/views/submissions/new.html.erb
<h1>New submission</h1>

<%= render 'form' %>

<%= link_to 'Back', neighborhoods_path %>